name: "UpdateDocsPls"
author: "Andrés Riquelme <andresfranco.rs@gmail.com>"
description: "Reads changes in a PR and remind contributors to update docs if appropriate"
inputs:
    config_path:
        description: "Path to configuration file which contains the articles: [files] relation. Defaults to .github/test_config.yaml"
        required: false
        default: ".github/UpdateDocsPls.yaml"
outputs:
    found_doc_related_changes:
        description: "If true, it means we found changes related to documentation articles"
    comment_content:
        description: "Formatted comment to be posted in the PR by another action"
runs:
    using: 'docker'
    image: 'Dockerfile'
branding:
    icon: 'book-open'
    color: 'purple'
