import unittest
from update_docs_pls.models import Results, FileResult, ArticleResult
from update_docs_pls.message import Messager

class TemplaterTest(unittest.TestCase):

    def setUp(self) -> None:
        base_url = 'https://www.example.com/'
        articles = []
        files = []

        for i in range(0, 10):
            articles.append(ArticleResult(f"Artile Nº {i}", f"{base_url}article-{i}"))

        for i in range(0, 10):
            files.append(FileResult(f"my_file_{i}.txt", f"{base_url}file-{i}"))

        self.templater = Messager(Results(articles, files))

    def test_add_title(self):
        self.templater.add_title()
        self.assertEqual("### Check if docs are up to date!\n", self.templater.message)

    def test_add_body(self):
        self.templater.add_body()
        expected = \
"""The following documentation articles might not be up to date: 
* [Artile Nº 0](https://www.example.com/article-0)
* [Artile Nº 1](https://www.example.com/article-1)
* [Artile Nº 2](https://www.example.com/article-2)
* [Artile Nº 3](https://www.example.com/article-3)
* [Artile Nº 4](https://www.example.com/article-4)
* [Artile Nº 5](https://www.example.com/article-5)
* [Artile Nº 6](https://www.example.com/article-6)
* [Artile Nº 7](https://www.example.com/article-7)
* [Artile Nº 8](https://www.example.com/article-8)
* [Artile Nº 9](https://www.example.com/article-9)\n"""
        self.assertEqual(expected, self.templater.message)

    def test_add_footer(self):
        self.templater.add_footer()
        expected = \
"""This message was generated by changes on the following files: 
* [my_file_0.txt](https://www.example.com/file-0)
* [my_file_1.txt](https://www.example.com/file-1)
* [my_file_2.txt](https://www.example.com/file-2)
* [my_file_3.txt](https://www.example.com/file-3)
* [my_file_4.txt](https://www.example.com/file-4)
* [my_file_5.txt](https://www.example.com/file-5)
* [my_file_6.txt](https://www.example.com/file-6)
* [my_file_7.txt](https://www.example.com/file-7)
* [my_file_8.txt](https://www.example.com/file-8)
* [my_file_9.txt](https://www.example.com/file-9)\n"""
        self.assertEqual(expected, self.templater.message)