from .models import Results
from .markdown import Markdown

class Messager:
    message: str

    def __init__(self, results: Results):
        self.results = results
        self.message = ""

    def add_title(self):
        self.message += f"{Markdown.title('Check if docs are up to date!', 3)}"

    def add_body(self):
        template = "The following documentation articles might not be up to date: \n{}"
        articles_links = [Markdown.link(i.name, i.url) for i in self.results.articles]

        self.message += template.format(Markdown.unordered_list(articles_links))

    def add_footer(self):
        template = "This message was generated by changes on the following files: \n{}"
        files = [Markdown.link(i.filename, i.url) for i in self.results.files]

        self.message += template.format(Markdown.unordered_list(files))

    def compose(self):
        self.add_title()
        self.add_body()
        self.add_footer()
        return self.message
