name: UpdateDocsPls
on:
    pull_request:
        branches:
            - master
        types:
            - opened
            - synchronize
jobs:
    check_docs:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: DocsReminder
                id: DocsReminder
                uses: corp-0/update-docs-pls@master
            -   name: Comment PR
                if: ${{ steps.DocsReminder.outputs.found_doc_related_changes }}
                uses: thollander/actions-comment-pull-request@v1
                with:
                    message: ${{ steps.DocsReminder.outputs.comment_content }}
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
